project"Game"
	kind"ConsoleApp"
	language"C++"
	cppdialect"C++17"
	buildoptions"/utf-8"
	targetdir("../bin/"..outputdir.."/%{prj.name}")	
	objdir("../bin-int/"..outputdir.."/%{prj.name}")
	files{
		"Src/**.h",
		"Src/**.cpp"
	}
	includedirs{
		"%{ThirdPartIncludeDir.spdlog}",
		"%{ThirdPartIncludeDir.GLM}",
		"%{ThirdPartIncludeDir.GLFW}",
		"%{ThirdPartIncludeDir.IMGUI}",
		"DM/Src"
	}
	links{
		"DM"
	}
	filter"system:windows"
		systemversion"latest"
		defines{
			"DM_PLATFORM_WINDOWS"
		}
	filter"configurations:Debug"
		defines"DM_DEBUG"
		runtime"Debug"
		symbols"on"
	filter"configurations:Release"
		defines"DM_RELEASE"
		runtime"Release"
		optimize"on"