project "Reflect"
    kind"SharedLib"
    language"C++"
    cppdialect"C++17"
    staticruntime"off"
    targetdir("../../bin/"..outputdir.."/%{prj.name}")
    objdir("../../bin-int/"..outputdir.."/%{prj.name}")
    files{
        "Src/**.h",
        "Src/**.cpp",
        "GeneratedCode/**.h",
        "GeneratedCode/**.cpp",
    }
    includedirs{
        "GeneratedCode",
        "Src",
        "../%{prj.name}",
        "%{ThirdPartIncludeDir.json}",
        "%{ThirdPartIncludeDir.entt}",
        "%{wks.basedir}/"..EngineName.."/Src"
    }
    defines{
            "REFLECT_PROJECT"
        }
    filter"configurations:Debug"
		runtime"Debug"
		symbols"on"
	filter"configurations:Release"
		runtime"Release"
		optimize"on"
    filter"system:windows"
        defines{
            "DM_PLATFORM_WINDOWS"
        }
        postbuildcommands{
			("{COPY} %{cfg.buildtarget.relpath} %{wks.basedir}/bin/"..outputdir.."/"..EngineName)
		}