project"Editor"
	kind"ConsoleApp"
	targetdir("../bin/"..outputdir.."/%{prj.name}")	
	objdir("../bin-int/"..outputdir.."/%{prj.name}")
	files{
		"Src/**.h",
		"Src/**.cpp"
	}
	includedirs{
		"%{ThirdPartIncludeDir.spdlog}",
		"%{ThirdPartIncludeDir.GLM}",
		"%{ThirdPartIncludeDir.GLFW}",
		"%{ThirdPartIncludeDir.IMGUI}",
		"%{ThirdPartIncludeDir.entt}",
		"%{ThirdPartIncludeDir.yaml_cpp}",
		"Src",
		"%{wks.basedir}/DM/Src"
	}
	links{
		"DM",
		"yaml_cpp"
	}
    libdirs{
        "%{wks.basedir}/"..EngineName.."bin/"..outputdir.."/"..EngineName,
    }
	filter"system:windows"
		systemversion"latest"
		defines{
			"DM_PLATFORM_WINDOWS"
		}
	filter"configurations:Debug"
		defines"DM_DEBUG"
		runtime"Debug"
		symbols"on"
		
	filter"configurations:Release"
		defines"DM_RELEASE"
		runtime"Release"
		optimize"on"