project "Reflection"
    kind"SharedLib"
    targetdir("../../bin/"..outputdir.."/%{prj.name}")
    objdir("../../bin-int/"..outputdir.."/%{prj.name}")
    files{
        "./Mirror/**.h",
        "./Mirror/**.cpp",
        "./GeneratedCode/**.h",
        "./GeneratedCode/**.cpp",
    }
    includedirs{
        "./GeneratedCode",
        "./Mirror",
    }
    defines{
            "REFLECT_PROJECT"
        }
    filter"configurations:Debug"
		runtime"Debug"
		symbols"on"
	filter"configurations:Release"
		runtime"Release"
		optimize"on"
    filter"system:windows"
        defines{
            "DM_PLATFORM_WINDOWS"
        }
        postbuildcommands{
			("{COPY} %{cfg.buildtarget.relpath} %{wks.basedir}/bin/"..outputdir.."/"..EngineName)
		}